version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 27081:80
    container_name: wxcloud_zmschool-serverless
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=zmschool-serverless
      - role=container
    environment:
      # 使用本地调试 MySQL 时，需要填入如下环境变量，并启动 MySQL 代理服务
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=k7tXbBYr
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-o8me80pg.sql.tencentcdb.com:24759
networks:
  default:
    external:
      name: wxcb0
